config/routes.rb
Rails.application.routes.draw do
  resources :dogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def new
    @dog = Dog.new
  end

  def create
    dog = Dog.create(dog_params)

    redirect_to dogs_path
  end

  def edit
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :motto)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/edit.html.erb
<h1>Dogs#edit</h1>
<p>Find me in app/views/dogs/edit.html.erb</p>

app/views/dogs/index.html.erb
<h1>Dogs#index</h1>
<p>Find me in app/views/dogs/index.html.erb</p>
<ul>
  <% @dogs.each do |dog| %>
    <li><%= link_to dog.name, dog_path(dog) %></li>
  <% end %>
</ul>

app/views/dogs/new.html.erb
<h1>Dogs#new</h1>
<p>Find me in app/views/dogs/new.html.erb</p>

app/views/dogs/show.html.erb
<h1><%= @dog.name %></h1>
<p>"<%= @dog.motto %>"</p>

<%= link_to 'Remove', @dog, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>